default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: qconcursos_development

test:
  <<: *default
  database: qconcursos_test

production:
  <<: *default
  database: qconcursos_production
  username: qconcursos
  password: <%= ENV['QCONCURSOS_DATABASE_PASSWORD'] %>
